name: Build Rust App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rgwood/luau_builder:latest
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Build Rust app
      run: cargo build --target x86_64-unknown-linux-musl

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-app
        path: target/x86_64-unknown-linux-musl/debug/*
