name: Build Rust App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull luau_builder image
      run: docker pull ghcr.io/rgwood/luau_builder:latest

    - name: Build Rust app
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app ghcr.io/rgwood/luau_builder:latest \
        cargo build --target x86_64-unknown-linux-musl

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rust-app
        path: target/x86_64-unknown-linux-musl/debug/your_app_name
